title: NL-RSE
author: nl-rse
email: info@nl-rse.org
description: > # this means to ignore newlines until "baseurl:"
  The community of Research Software Engineers
  from Dutch universities, knowledge institutes, companies and
  other relevant organizations for sharing knowledge, organizing
  meetings and raising awareness for the scientific recognition of research software.
twitter_username: nl_rse
github_username:  nl-rse

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - _pages/community.md
 - _pages/join.md
 - _pages/communication.md
 - _pages/events.md


exclude: _events/202X-MM-DD-meetup.TEMPLATE.md

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  pages:
    output: true
  events:
    output: true
